replicaCount: 1

image:
  repository: roy-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30007

app:
  name: roy-app

config:
  customMessage: "Hello from Helm! roy"
  appGreeting: "ברוך הבא"
  username: "roy"

redis:
  host: redis
  port: "6379"

secret:
  redisPassword: "redispass123"
  secretKey: "mySuperSecret123"
  apiKey: "my-api-key-456"
