version: '3.8'

services:
  postgres_db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U royyo -d prod_database"]
      interval: 10s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    depends_on:
      postgres_db:
        condition: service_healthy
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./frontend/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "start"]

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  postgres_data:
