version: '3.8'

services:
  postgres_db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U royyo -d dev_database"]
      interval: 5s
      retries: 5
      start_period: 15s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.dev
    ports:
      - "5000:5000"
    depends_on:
      postgres_db:
        condition: service_healthy
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
