apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  CUSTOM_MESSAGE: {{ .Values.config.customMessage | quote }}
  APP_GREETING: {{ .Values.config.appGreeting | quote }}
  USERNAME: {{ .Values.config.username | quote }}
