# --- SECRETS ---
apiVersion: v1
kind: Secret
metadata:
  name: royapp-secret
type: Opaque
data:
  API_KEY: c29tZS1zZWNyZXQtdmFsdWU=  # some-secret-value
  REDIS_PASSWORD: ""  # אפשר להוסיף בסיסמה בהמשך
