replicaCount: 1

image:
  repository: roy-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30007

redis:
  enabled: true
  host: redis
  port: 6379

config:
  customMessage: "Hello from DEV!"

secret:
  key: "supersecretdev"

env:
  flaskEnv: development
  debug: true

ingress:
  enabled: false
  host: dev.local
